//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceApp.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AttendanceApp.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string aboutus {
            get {
                return ResourceManager.GetString("aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Leaves.
        /// </summary>
        internal static string approveLeaves {
            get {
                return ResourceManager.GetString("approveLeaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Reasons.
        /// </summary>
        internal static string approveReasons {
            get {
                return ResourceManager.GetString("approveReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string arabicLbl {
            get {
                return ResourceManager.GetString("arabicLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating user....
        /// </summary>
        internal static string authenticatingUser {
            get {
                return ResourceManager.GetString("authenticatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In/Check Out.
        /// </summary>
        internal static string checkInCheckOut {
            get {
                return ResourceManager.GetString("checkInCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming (Check IN).
        /// </summary>
        internal static string comingCheckIn {
            get {
                return ResourceManager.GetString("comingCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations.
        /// </summary>
        internal static string configurations {
            get {
                return ResourceManager.GetString("configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Settings.
        /// </summary>
        internal static string configurationSettings {
            get {
                return ResourceManager.GetString("configurationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration URL.
        /// </summary>
        internal static string configurationURL {
            get {
                return ResourceManager.GetString("configurationURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string currentPassword {
            get {
                return ResourceManager.GetString("currentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashborad.
        /// </summary>
        internal static string dashborad {
            get {
                return ResourceManager.GetString("dashborad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Manager.
        /// </summary>
        internal static string directManager {
            get {
                return ResourceManager.GetString("directManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        internal static string endTime {
            get {
                return ResourceManager.GetString("endTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Url.
        /// </summary>
        internal static string enterUrl {
            get {
                return ResourceManager.GetString("enterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Data.
        /// </summary>
        internal static string ErrorLoadingData {
            get {
                return ResourceManager.GetString("ErrorLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string fromDate {
            get {
                return ResourceManager.GetString("fromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganter TA System.
        /// </summary>
        internal static string ganterTASystem {
            get {
                return ResourceManager.GetString("ganterTASystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy.
        /// </summary>
        internal static string happy {
            get {
                return ResourceManager.GetString("happy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Details.
        /// </summary>
        internal static string invalidUserDetails {
            get {
                return ResourceManager.GetString("invalidUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Request.
        /// </summary>
        internal static string leaveRequest {
            get {
                return ResourceManager.GetString("leaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving (Check Out).
        /// </summary>
        internal static string leavingCheckOut {
            get {
                return ResourceManager.GetString("leavingCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string loginBtn {
            get {
                return ResourceManager.GetString("loginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string loginLbl {
            get {
                return ResourceManager.GetString("loginLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Settings.
        /// </summary>
        internal static string moreSettings {
            get {
                return ResourceManager.GetString("moreSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Attendance.
        /// </summary>
        internal static string myAttendance {
            get {
                return ResourceManager.GetString("myAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        internal static string neutral {
            get {
                return ResourceManager.GetString("neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your network connection..
        /// </summary>
        internal static string pleaseCheckYourNetworkConnection {
            get {
                return ResourceManager.GetString("pleaseCheckYourNetworkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose direction.
        /// </summary>
        internal static string pleaseChooseDirection {
            get {
                return ResourceManager.GetString("pleaseChooseDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a function.
        /// </summary>
        internal static string pleaseChooseFunction {
            get {
                return ResourceManager.GetString("pleaseChooseFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable your location service..
        /// </summary>
        internal static string pleaseEnableYourLocationService {
            get {
                return ResourceManager.GetString("pleaseEnableYourLocationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Password..
        /// </summary>
        internal static string pleaseProvidePassword {
            get {
                return ResourceManager.GetString("pleaseProvidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide User Name..
        /// </summary>
        internal static string pleaseProvideUserName {
            get {
                return ResourceManager.GetString("pleaseProvideUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select happiness option.
        /// </summary>
        internal static string pleaseSelectHappinessOption {
            get {
                return ResourceManager.GetString("pleaseSelectHappinessOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select reason.
        /// </summary>
        internal static string pleaseSelectReason {
            get {
                return ResourceManager.GetString("pleaseSelectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string pleaseWait {
            get {
                return ResourceManager.GetString("pleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Request.
        /// </summary>
        internal static string reason_Request {
            get {
                return ResourceManager.GetString("reason Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Date.
        /// </summary>
        internal static string reasonDate {
            get {
                return ResourceManager.GetString("reasonDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Request.
        /// </summary>
        internal static string reasonRequest {
            get {
                return ResourceManager.GetString("reasonRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons.
        /// </summary>
        internal static string reasons {
            get {
                return ResourceManager.GetString("reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Type.
        /// </summary>
        internal static string reasonType {
            get {
                return ResourceManager.GetString("reasonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string remarks {
            get {
                return ResourceManager.GetString("remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string resetPassword {
            get {
                return ResourceManager.GetString("resetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sad.
        /// </summary>
        internal static string sad {
            get {
                return ResourceManager.GetString("sad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string startTime {
            get {
                return ResourceManager.GetString("startTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully.
        /// </summary>
        internal static string successfully {
            get {
                return ResourceManager.GetString("successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time In.
        /// </summary>
        internal static string timeIn {
            get {
                return ResourceManager.GetString("timeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out.
        /// </summary>
        internal static string timeOut {
            get {
                return ResourceManager.GetString("timeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string toDate {
            get {
                return ResourceManager.GetString("toDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unjustified Violations.
        /// </summary>
        internal static string unjustifiedViolations {
            get {
                return ResourceManager.GetString("unjustifiedViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password.
        /// </summary>
        internal static string updatePassword {
            get {
                return ResourceManager.GetString("updatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation Balance.
        /// </summary>
        internal static string vacationBalance {
            get {
                return ResourceManager.GetString("vacationBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio.
        /// </summary>
        internal static string visualStudio {
            get {
                return ResourceManager.GetString("visualStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are Checked.
        /// </summary>
        internal static string youAreChecked {
            get {
                return ResourceManager.GetString("youAreChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in location.
        /// </summary>
        internal static string youAreInLocation {
            get {
                return ResourceManager.GetString("youAreInLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are out of location.
        /// </summary>
        internal static string youAreOutOfLocation {
            get {
                return ResourceManager.GetString("youAreOutOfLocation", resourceCulture);
            }
        }
    }
}
